create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, complaints TEXT, diagnosis TEXT, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, phone varchar(255), specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, phone varchar(255), specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, notes TEXT, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, prescription_date date not null, appointment_id bigint, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, medications TEXT not null, notes TEXT, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
create table appointments (appointment_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, status enum ('CANCELLED','COMPLETED','NO_SHOW','SCHEDULED') not null, primary key (id)) engine=InnoDB;
create table doctors (id bigint not null auto_increment, department varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, specialization varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table patients (birth_date date, id bigint not null auto_increment, tc_no varchar(11) not null, address TEXT, blood_type varchar(255), email varchar(255), first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255), phone varchar(255), primary key (id)) engine=InnoDB;
create table prescriptions (duration_days integer, appointment_id bigint, created_date datetime(6) not null, doctor_id bigint not null, id bigint not null auto_increment, patient_id bigint not null, dosage TEXT, instructions TEXT, notes TEXT, prescription_text TEXT not null, primary key (id)) engine=InnoDB;
create table secretaries (id bigint not null auto_increment, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, username varchar(255) not null, primary key (id)) engine=InnoDB;
create table triage_records (blood_pressure_diastolic integer, blood_pressure_systolic integer, heart_rate integer, respiratory_rate integer, temperature float(53), id bigint not null auto_increment, patient_id bigint not null, triage_date datetime(6) not null, notes TEXT, performed_by varchar(255), status varchar(255) not null, symptoms TEXT, priority enum ('CRITICAL','NON_URGENT','ROUTINE','SEMI_URGENT','URGENT') not null, primary key (id)) engine=InnoDB;
alter table doctors add constraint UK15xrlsp4drthssb0ns4pghcfk unique (username);
alter table patients add constraint UK9iaa1pk0xlx62hdqhvbai4fvm unique (tc_no);
alter table secretaries add constraint UKjtcnqb5hnc3llkbank9symakb unique (username);
alter table appointments add constraint FKmujeo4tymoo98cmf7uj3vsv76 foreign key (doctor_id) references doctors (id);
alter table appointments add constraint FK8exap5wmg8kmb1g1rx3by21yt foreign key (patient_id) references patients (id);
alter table prescriptions add constraint FKe2fpvlkkcgcd40k4ufyyju2al foreign key (appointment_id) references appointments (id);
alter table prescriptions add constraint FK24chc88e4so7cd6melh11rv6 foreign key (doctor_id) references doctors (id);
alter table prescriptions add constraint FKqydyol76jn1o37k1bdbkjgq74 foreign key (patient_id) references patients (id);
alter table triage_records add constraint FKffdxtqainqied8g1vtvl73u0o foreign key (patient_id) references patients (id);
